/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContentBar: typeof import('./components/ContentBar.vue')['default']
    ContentVuer: typeof import('./components/ContentVuer.vue')['default']
    ContextCard: typeof import('./components/ContextCard.vue')['default']
    ContextHelp: typeof import('./components/ContextHelp.vue')['default']
    CustomSplitter: typeof import('./components/CustomSplitter.vue')['default']
    DatasetHeader: typeof import('./components/DatasetHeader.vue')['default']
    DialogToolbarContent: typeof import('./components/DialogToolbarContent.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconArrowDown: typeof import('@element-plus/icons-vue')['ArrowDown']
    ElIconArrowUp: typeof import('@element-plus/icons-vue')['ArrowUp']
    ElIconCompass: typeof import('@element-plus/icons-vue')['Compass']
    ElIconEditPen: typeof import('@element-plus/icons-vue')['EditPen']
    ElIconMoreFilled: typeof import('@element-plus/icons-vue')['MoreFilled']
    ElIconShare: typeof import('@element-plus/icons-vue')['Share']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Flatmap: typeof import('./components/viewers/Flatmap.vue')['default']
    FlatmapContextCard: typeof import('./components/FlatmapContextCard.vue')['default']
    Iframe: typeof import('./components/viewers/Iframe.vue')['default']
    MapContent: typeof import('./components/MapContent.vue')['default']
    MultiFlatmap: typeof import('./components/viewers/MultiFlatmap.vue')['default']
    Plot: typeof import('./components/viewers/Plot.vue')['default']
    ResizeSensor: typeof import('./components/ResizeSensor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scaffold: typeof import('./components/viewers/Scaffold.vue')['default']
    SearchControls: typeof import('./components/SearchControls.vue')['default']
    Simulation: typeof import('./components/viewers/Simulation.vue')['default']
    SplitDialog: typeof import('./components/SplitDialog.vue')['default']
    SplitFlow: typeof import('./components/SplitFlow.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
